---
- name: Setup Dev Bastion Host
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC setup variable
      include_vars: vars/bastion_setup

    - name: Import VPC setup variable
      include_vars: vars/output_vars

    - name: Create dev ec2 key
      ec2_key:
          name: devpro-key
          region: "{{region}}"
      register: key_out

    - name: Save private key into file bastion-key.pem
      copy:
        content: "{{key_out.private_key}}"
        dest: "./bastion-key.pem"
        mode: 0600
      when: key_out.changed

    - name: Bastion host SG
      ec2_group:
          name: Bastion-host-sg
          description: Allow port 22 from everywhere and all port within sg
          region: "{{region}}"
          vpc_id: "{{vpcid}}"
          rules:
            - proto: tcp
              from_port: 22
              to_port: 22
              cidr_ip: "{{MYIP}}"
      register: BastionSG_out

    - name: Create bastion host
      ec2:
          key_name: "{{key_out}}"
          region: "{{region}}"
          instance_type: t2.micro
          image: "{{bastion_ami}}"
          wait: yes
          wait_timeout: 300
          instance_tags:
            Name: "Bastion_host"
            Project: dev
            Owner: Bash
          exact_count: 1
          count_tag:
            Name: "Bastion_host"
            Project: dev
            Owner: Bash
          group_id: "{{BastionSG_out.group_id}}"
          vpc_subnet_id: "{{pubsub1id}}"
      register: bastionhost_out




